create schema if not exists public;

comment on schema public is 'standard public schema';

alter schema public owner to "lunchTimeAppUser";

create sequence hibernate_sequence;

alter sequence hibernate_sequence owner to "lunchTimeAppUser";

create table category_food
(
    id bigint not null
        constraint category_food_pkey
            primary key,
    is_deleted boolean default false,
    name varchar(255)
);

alter table category_food owner to "lunchTimeAppUser";

create table dish
(
    id bigint not null
        constraint dish_pkey
            primary key,
    ingredients varchar(255),
    is_deleted boolean default false,
    name varchar(30),
    categoryfood_id bigint not null
        constraint fk7guodmtsva3lbudcetvn4hss
            references category_food
);

alter table dish owner to "lunchTimeAppUser";

create table event_category
(
    id bigint generated by default as identity
        constraint event_category_pkey
            primary key,
    category varchar(255) not null
);

alter table event_category owner to "lunchTimeAppUser";

create table order_status
(
    id bigint generated by default as identity
        constraint order_status_pkey
            primary key,
    created_at timestamp,
    created_by bigint,
    is_deleted boolean default false,
    modify_at timestamp,
    modify_by bigint,
    name varchar(32) not null
);

alter table order_status owner to "lunchTimeAppUser";

create table person
(
    id bigint generated by default as identity
        constraint person_pkey
            primary key,
    created_at timestamp,
    created_by bigint,
    email varchar(255)
        constraint uk_fwmwi44u55bo4rvwsv0cln012
            unique,
    is_deleted boolean,
    modify_at timestamp,
    modify_by bigint,
    name varchar(255),
    password varchar(255),
    phone_number varchar(255),
    avatar_url varchar(255),
    role_id bigint,
    status varchar(50) default 'ACTIVE'::character varying
);

alter table person owner to "lunchTimeAppUser";

create table restaurant
(
    id bigint generated by default as identity
        constraint restaurant_pkey
            primary key,
    created_at timestamp,
    created_by bigint,
    description varchar(255),
    email varchar(255),
    is_deleted boolean,
    latitude real,
    longitude real,
    modify_at timestamp,
    modify_by bigint,
    name varchar(100),
    tables integer,
    text_address varchar(255),
    website varchar(255),
    working_time varchar(255),
    person_id bigint not null
        constraint fkdshsx0e4udxc2mjv94g36g2i0
            references person
);

alter table restaurant owner to "lunchTimeAppUser";

create table event
(
    id bigint generated by default as identity
        constraint event_pkey
            primary key,
    date timestamp not null,
    description varchar(999),
    image varchar(255) not null,
    is_deleted boolean,
    name varchar(255),
    event_category_id bigint not null
        constraint fknk9w760hnelms32e9oqecw6ru
            references event_category,
    restaurant bigint not null
        constraint fkhxleeencyow395ho1le2kwslm
            references restaurant
);

alter table event owner to "lunchTimeAppUser";

create table feedback
(
    id bigint generated by default as identity
        constraint feedback_pkey
            primary key,
    counter_dislike integer default 0,
    counter_like integer default 0,
    date timestamp not null,
    description varchar(1000) not null,
    is_active boolean default true,
    person_id bigint not null
        constraint fk9fngeswvwow8hbw483eflv3l5
            references person,
    restaurant_id bigint not null
        constraint fkt9gnevqw4oo5jnbv4e68tu0ua
            references restaurant
);

alter table feedback owner to "lunchTimeAppUser";

create table menu_item_dish
(
    id bigint not null
        constraint menu_item_dish_pkey
            primary key,
    image_url varchar(255),
    is_deleted boolean default false,
    portion_price bigint not null,
    portion_size varchar(30),
    portion_unit bigint,
    dish_id bigint not null
        constraint fkpmq3wkvyh05wsbfc6eryvqow8
            references dish,
    restaurant_id bigint
        constraint fkhfhyqjp21e022alx1adi9hffy
            references restaurant
);

alter table menu_item_dish owner to "lunchTimeAppUser";

create table restaurant_table
(
    id bigint generated by default as identity
        constraint restaurant_table_pkey
            primary key,
    capacity integer not null,
    created_at timestamp,
    created_by bigint,
    description varchar(999),
    is_deleted boolean default false,
    modify_at timestamp,
    modify_by bigint,
    number integer not null,
    restaurant_id bigint not null
        constraint fk3pdovxhxtwrb5kboju0qs21tn
            references restaurant
);

alter table restaurant_table owner to "lunchTimeAppUser";

create table ordering
(
    id bigint generated by default as identity
        constraint ordering_pkey
            primary key,
    created_at timestamp,
    created_by bigint,
    description varchar(999),
    dish_details_id bigint,
    finish_time timestamp not null,
    is_deleted boolean default false,
    modify_at timestamp,
    modify_by bigint,
    start_time timestamp not null,
    visitors integer not null,
    waiter_id bigint,
    person_id bigint not null
        constraint fkiqcy2hdvtf3uju0ryqpbk3g6s
            references person,
    status_id bigint
        constraint fk56tr0ppum4b3n3q9istj0mo1h
            references order_status,
    table_id bigint not null
        constraint fkoy8ioyrjdp5j7i5cem0t7oegy
            references restaurant_table
);

alter table ordering owner to "lunchTimeAppUser";

create table role
(
    id bigint not null
        constraint role_pkey
            primary key,
    name varchar(255)
);

alter table role owner to "lunchTimeAppUser";

create table user_roles
(
    role_id bigint
        constraint fkrhfovtciq1l558cw6udg0h0d3
            references role,
    user_id bigint not null
        constraint user_roles_pkey
            primary key
        constraint fkck7bkebbxnx8ilo4lcmemi8gf
            references person
);

alter table user_roles owner to "lunchTimeAppUser";

