create table order_status
(
    id         bigint generated by default as identity
        constraint order_status_pkey
            primary key,
    created_at timestamp,
    created_by bigint,
    is_deleted boolean default false,
    modify_at  timestamp,
    modify_by  bigint,
    name       varchar(32) not null
);

alter table order_status
    owner to "lunchTimeAppUser";

create table restaurant_table
(
    id            bigint generated by default as identity
        constraint restaurant_table_pkey
            primary key,
    capacity      integer not null,
    created_at    timestamp,
    created_by    bigint,
    description   varchar(999),
    is_deleted    boolean default false,
    modify_at     timestamp,
    modify_by     bigint,
    number        integer not null,
    restaurant_id bigint  not null
        constraint fk3pdovxhxtwrb5kboju0qs21tn
            references restaurant
);

alter table restaurant_table
    owner to "lunchTimeAppUser";

create table ordering
(
    id              bigint generated by default as identity
        constraint ordering_pkey
            primary key,
    created_at      timestamp,
    created_by      bigint,
    description     varchar(999),
    dish_details_id bigint,
    finish_time     timestamp not null,
    is_deleted      boolean default false,
    modify_at       timestamp,
    modify_by       bigint,
    start_time      timestamp not null,
    visitors        integer   not null,
    waiter_id       bigint,
    person_id       bigint    not null
        constraint fkiqcy2hdvtf3uju0ryqpbk3g6s
            references person,
    status_id       bigint
        constraint fk56tr0ppum4b3n3q9istj0mo1h
            references order_status,
    table_id        bigint    not null
        constraint fkoy8ioyrjdp5j7i5cem0t7oegy
            references restaurant_table
);

alter table ordering
    owner to "lunchTimeAppUser";

