alter table feedback
    drop column if exists counter_like;

alter table feedback
    add column counter_like;

create table feedback_person_id
(
    id bigint generated by default as identity
        constraint order_dish_pkey
            primary key,
    order_id bigint not null
        constraint ordering_pkey
            references ordering,
    menu_item_dish_id bigint not null
        constraint menu_item_dish_pkey
            references menu_item_dish,
    quantity integer not null
);

