alter table ordering
    drop column if exists dish_details_id;

create table order_dish
(
    id bigint generated by default as identity
        constraint order_dish_pkey
            primary key,
    order_id bigint not null
        constraint ordering_pkey
            references ordering,
    menu_item_dish_id bigint not null
        constraint menu_item_dish_pkey
            references menu_item_dish,
    quantity integer not null
);

