alter table feedback
    drop column if exists counter_like;

create table feedback_like
(
    id bigint generated by default as identity
        constraint feedback_like_pkey
            primary key,
    person_id bigint not null
        constraint person_pkey
            references person,
    feedback_id bigint not null
        constraint feedback_pkey
            references feedback
);

create table feedback_dislike
(
    id bigint generated by default as identity
        constraint feedback_dislike_pkey
            primary key,
    person_id bigint not null
        constraint person_pkey
            references person,
    feedback_id bigint not null
        constraint feedback_pkey
            references feedback
)
